bug:
  - head-branch: ['^fix/[a-zA-Z_-]+']

documentation:
  - changed-files:
    - any-glob-to-any-file: ['*.md']

feature:
  - head-branch: ['^feat/[a-zA-Z_-]+']

chore:
  - head-branch: ['^chore/[a-zA-Z_-]+']

refactor:
  - head-branch: ['^refactor/[a-zA-Z_-]+']
