export default [
  'CaseData',
	'CasePlan',
	'EmployeeFootprint',
	'EmployeeVitalSign',
	'MessageData',
	'OfflineEmployeeData',
	'OfflineRecord',
	'OfflineTOCCForm',
	'ServiceItemData',
	'ServiceRecord',
	'shift',
	'shiftRecord',
	'TOCCFormRecord',
	'OfflineServiceRecord',
	'ErrorLog',
]
