name: 'Generate Labels'

on:
- pull_request
- issues

jobs:
  labeler:
    permissions:
      contents: read
      # 要賦予 workflow PR的 write 權限才能上 label
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      env:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"
